# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37b6ce2cd0566b8e8dd8cb7773964b44713195c695f6d4c0ab354281c6113ffe67d7757e8a59e1efec101b962c46af13357a6d0dcfdb2ce1cd38b8d375c70fd3

test:
  secret_key_base: 00fdbf45970f0589cf401cb243a6d6ec73a7556b3889bfb7756f97309099102724fd074f1d10cfc338f92df88610c990632209ced8b590c12fbdacc00aa75f25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
